name=ESP32 BLE Keyboard
version=1.0.0
author=Gaurav Sharma
maintainer=Gaurav Sharma <ss3573509@gmail.com>
sentence=Bluetooth HID Keyboard library for ESP32 boards.
paragraph=Allows ESP32 boards to emulate a Bluetooth Low Energy HID keyboard.
category=Communication
url=https://github.com/gsgaurav0/ESP32-BLE-Keyboard
architectures=esp32
license=MIT